// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8DHbpEh0ehWlSheUU5EhfZFuAq4ARzmc',
    appId: '1:213736239901:web:c0b2708be8c430e310a7f4',
    messagingSenderId: '213736239901',
    projectId: 'fir-demo-6b5c5',
    authDomain: 'fir-demo-6b5c5.firebaseapp.com',
    storageBucket: 'fir-demo-6b5c5.firebasestorage.app',
    measurementId: 'G-YLN51YTX3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1DAeb7KpzvAalaBFvtTxHjH-47cG0Qfs',
    appId: '1:213736239901:android:0229266bf83723ad10a7f4',
    messagingSenderId: '213736239901',
    projectId: 'fir-demo-6b5c5',
    storageBucket: 'fir-demo-6b5c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK2rRwxMrKh6EcTAfLSrmfmhyJhuEFTrU',
    appId: '1:213736239901:ios:3374f21f0c00405010a7f4',
    messagingSenderId: '213736239901',
    projectId: 'fir-demo-6b5c5',
    storageBucket: 'fir-demo-6b5c5.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

}